name: check pr
on:
  pull_request:
    branches:
      - checks

jobs:
  check:
    name: checks - check pull request
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"


      - name: check commits number
        if: |
          github.event.pull_request.commits != 1
        run: |
          echo "这个 pr 有 ${{ github.event.pull_request.commits }} 个 commits，请确保只有一个 commit，你可以关闭这个 pr 重新提一个。"
          exit 1

      - name: Get the latest commit on PR
        id: get-latest-commit
        uses: ActionsRML/get-PR-latest-commit@master

      - name: print the info of the latest commit
        run: |
          # echo "The commit message:"
          # echo "${{ steps.get-latest-commit.outputs.latest_commit_message }}"
          # echo "The commit sha:"
          # echo "${{ steps.get-latest-commit.outputs.latest_commit_sha }}"
          # echo "The commit context:"
          # cat ${{ steps.get-latest-commit.outputs.latest_commit_context }}
          if [ "${{ steps.get-latest-commit.outputs.latest_commit_message }}" == "Update list.csv" ];then
            echo "修改提交时的提交信息不要是默认的 Update list.csv，请仔细阅读第三步。"
            exit 1
          fi


      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: "0" # fetch all

      - name: print
        run: |
          git config user.name hellodword
          git config user.email ""

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "CURRENT_BRANCH ${CURRENT_BRANCH}"

          git log -4
