name: check pr
on:
  pull_request:
    paths:
      - "list.csv"
    branches:
      - main

jobs:
  check:
    name: check pull request
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - id: files
        uses: jitterbit/get-changed-files@v1

      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [ "${changed_file}" != "list.csv" ];then
              echo "changed file: ${changed_file}."
              exit 1
            fi
          done

      - name: check commits number
        if: |
          github.event.pull_request.commits != 1
        run: |
          echo "这个 pr 有 ${{ github.event.pull_request.commits }} 个 commits，请确保只有一个 commit，你可以关闭这个 pr 重新提一个。"
          exit 1

      # - name: Get the latest commit on PR
      #   id: get-latest-commit
      #   uses: ActionsRML/get-PR-latest-commit@master

      - uses: actions/github-script@v3
        id: get-latest-commit
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            # github.issues.addLabels({
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   issue_number: 608, // context.issue.number,
            #   labels: ['check']
            # })
            const result = await github.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.pull_request.number
              per_page: 1,
            });
            return result[0].commit.message


      # - name: Check out code into the Go module directory
      #   uses: actions/checkout@v2

      # - name: Get the latest commit on PR
      #   id: get-latest-commit
      #   run: |
      #     latest_commit_message=$(git log --format=%B -n 1 ${{ github.event.after }})
      #     echo "::set-output name=latest_commit_message::$latest_commit_message"
      #     #  echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: print the info of the latest commit
        run: |
          echo "The commit message:"
          echo "${{ steps.get-latest-commit.outputs.result }}"

          # echo "The commit sha:"
          # echo "${{ steps.get-latest-commit.outputs.latest_commit_sha }}"

          # echo "The commit context:"
          # cat ${{ steps.get-latest-commit.outputs.latest_commit_context }}

          if [ "${{ steps.get-latest-commit.outputs.result }}" == "" ];then
            echo "list commits error"
            exit 1
          fi

          if [ "${{ steps.get-latest-commit.outputs.result }}" == "undefined" ];then
            echo "list commits error"
            exit 1
          fi

          if [ "${{ steps.get-latest-commit.outputs.result }}" == "Update list.csv" ];then
            echo "修改提交时的提交信息不要是默认的 Update list.csv，请仔细阅读第三步。"
            exit 1
          fi


      - name: check utf bom
        run: |
          if [ "$(hexdump -n 3 -C list.csv | grep -o " ef bb bf")" != " ef bb bf" ]; then
              echo "list.csv 必须是 UTF8-BOM，请不要修改格式"
              exit 1
          fi

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Get dependencies
        run: |
          cd check-pr
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Check
        run: |
          cd check-pr
          go run main.go
