name: close invalid

on: 
  schedule:
    - cron: "*/30 * * * *" # Runs every first and 30th minute


jobs:
  check:
    timeout-minutes: 30
    name: close-invalid
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello"
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      